name: Paloma
version: 0.1.0
github: "Pappa/Paloma"
license: BSD3
author: "Pappa"
maintainer: "dr.pappa@gmail.com"
copyright: "MIT"

description: Please see the README on GitHub at <https://github.com/Pappa/Paloma#readme>

dependencies:
  - base >= 4.7 && < 5
  - aws-lambda-haskell-runtime >= 2.0.3
  - aeson
  - amazonka-dynamodb >= 1.6.1
  - text

library:
  source-dirs: src

executables:
  bootstrap:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -O2
      - -static
      - -with-rtsopts=-N
    cc-options: -static
    ld-options: -static -pthread
    dependencies:
      - Paloma

default-extensions:
  - TemplateHaskell
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
