service: paloma
# app and org for use with dashboard.serverless.com
app: paloma
org: drpappa

package:
  artifact: build/function.zip

provider:
  name: aws
  profile: serverless-agent
  runtime: provided
  region: eu-west-1

functions:
  hello:
    handler: src/Lib.handler
    layers:
      - arn:aws:lambda:eu-west-1:785355572843:layer:aws-haskell-runtime:2
